export const ActionType = {
  ON_FAILURE: "FETCH_EXAMPLE_FAILURE",
  ON_SUCCESS: "FETCH_EXAMPLE_SUCCESS",
  ON_REQUEST: "FETCH_EXAMPLE_REQUEST",

  ON_INREMENT: "FETCH_ON_INREMENT",
  ON_DECREMENT: "FETCH_ON_DECREMENT",
};
